### ISSUE TITLE
Unify gh actions and permissions

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#496]
In inspire we have 2 types of packages services and libraries, we should unify the gh-actions and permissions to follow the following

- build (optional only for services)
- lint -> it should run pre-commit repo configuration
- tests
- pull-request-main
- push-main

Additionally, all libraries should use the bump2version python package to bump the version after a push to master. Some libraries still use `autosemver`, which should be removed!

More specifically the pull-request-main should look something like:

### Services

```
name: Pull request main

on:
  pull_request_target:
    branches: [main]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      ref: ${{ github.ref }}
  test:
    uses: ./.github/workflows/test.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
```

```
name: Push main

on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      ref: ${{ github.ref }}
  test:
    uses: ./.github/workflows/test.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: send event
        uses: cern-sis/gh-workflows/.github/actions/kubernetes-project-new-images@v6.2.0
        with:
          event-type: update
          images: |
            cern-sis/inspire/backoffice@${{ needs.test.outputs.image-id }}
          token: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES }}

```

### Packages

```
name: Pull request main

on:
  pull_request_target:
    branches: [main]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      ref: ${{ github.ref }}
  test:
    uses: ./.github/workflows/test.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
```

```
name: Push master

on:
  push:
    branches:
      - master

jobs:

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      ref: ${{ github.ref }}

  tests:
    uses: ./.github/workflows/tests.yml
  
  bump_version:
    needs: [tests]
    uses: ./.github/workflows/bump.yml
  
  publish_package:
    needs: bump_version
    uses: ./.github/workflows/build-and-publish.yml
```

# Package list
- inspire-utils
- inspire-schemas
- inspire-dojson
- inspire-json-merger
- inspire-matcher
- inspire-query-parser

# Services
- inspirehep
- inspire-classifier
- workflows
- backoffice
- refextract
