### ISSUE TITLE
airflow: scale pipelines

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [cern-sis/issues-inspire#945]
## Description

Currently for scenarios with big loads, our pipeline does not scale correctly. The triggerer gets very busy and the tasks are scheduled very slowly. As we grow and we put more things in airflow, it is essential to find a solution to this problem

## Work involved
* Check possible alternatives:
   *  more schedulers - ❌ not helpful for mapped tasks, helpful for dags
    * batching - a given mapped tasks handles multples records - ❌ only if we really need it.  It adds to much complexity
    * use dags instead of mapped tasks? ( greatly increases db IO. Harder to differentiate harvests. ❌ only if we really need it.
   * isolated celery queues ( cds queue, authors queue, literature queue etc... ❌ this is not really implemented via Helm chart, unless we kustomize the charts. this seems to overkill right now - a viable alternative are [Pools](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/pools.html)
   * more concurrent tasks `AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG` - ✅ set to 64
   * Make `dev` and `prod` have the same settings ✅
   * Verify cds record account 19-05-2025 issue ( to be solved in another ticket) 

## Acceptance criteria

* Our pipelines are able to scale in big load scenarios

**Comment by DonHaul** [comment]
testing configs in dev
https://github.com/cern-sis/kubernetes-airflow/commit/162ca93373b8349f6ec37eb5b8c32aa1959e51bb

**Comment by DonHaul** [comment]
Config in here seems to be stable:
https://github.com/cern-sis/kubernetes-airflow/blob/2ba6f580d7103c7c76769edc8170959d102baaa6/airflow/environments/airflow-inspire-dev/kustomization.yml

```
workers:
        logGroomerSidecar:
          enabled: false
        replicas: 8
        resources:
          requests:
            memory: 4Gi
          limits:
            memory: 4Gi
...
        - name: AIRFLOW__SCHEDULER__TASK_QUEUED_TIMEOUT
          value: '900'
        - name: AIRFLOW__SCHEDULER__MAX_TIS_PER_QUERY
          value: '128'
        - name: AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG
          value: '64'
        - name: AIRFLOW__KUBERNETES_EXECUTOR__WORKER_PODS_CREATION_BATCH_SIZE
          value: '4'
        - name: AIRFLOW__CORE__MAX_MAP_LENGTH
          value: '4096'
        - name: AIRFLOW__CORE__PARALLELISM
          value: '256'
        - name: AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG
          value: '64'
        - name: AIRFLOW__CELERY__WORKER_CONCURRENCY
          value: '16'
```
After this, by setting:
- ` AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: 128` 
- `AIRFLOW__CELERY__WORKER_CONCURRENCY: 32`
And running a heavy job, the whole cluster went down.

Currently had to revert back due to this cluster limitation.

Next actions:
- Isolate each namespace or equivalent solution. if one namespace fails it should bring down all the other ones. current solution is putting dbs on dbod https://github.com/cern-sis/infrastructure/issues/84
